server:
  port: 8087
spring:
  application:
    name: auth-service
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/erueka
    registry-fetch-interval-seconds: 10
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
leyou:
  jwt:
    secret : leyou@Longin(Auth)*^31&Ma%
    pubKeyPath:  #公钥地址
    priKeyPath:    #私钥地址
    expire: 30   #过期时间单位分钟
    cookieName: LY_TOKEN