server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name: search-service
      cluster-nodes: 127.0.0.1
  jackson:
    default-property-inclusion: non_null
eureka:
  client:
    service-url:
      defaultZone: htpp:127.0.0.1:8089/huke
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5
