server:
  port: 8083
spring:
  application:
    name: search-service
  data:
    elasticsearch:
      cluster-name:
      cluster-nodes:
eureka:
  client:
    service-url:
      defaultZone:
    registry-fetch-interval-seconds: 10
  instance:
    lease-expiration-duration-in-seconds: 5
    lease-renewal-interval-in-seconds: 5